# Data Preprocessing

## Importing the libraries

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


## Importing Dataset

In [5]:
data_set = pd.read_csv('Covid_Data.csv')
X = data_set.iloc[:, :-1].values
y = data_set.iloc[:, -1].values

In [6]:
print(X)


[[10.0 'Normal' 'no' 'no' 97.0]
 [12.0 'Normal' 'no' 'no' 97.0]
 [15.0 'Normal' 'no' 'no' 94.0]
 [10.0 'Normal' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Normal' 'no' 'no' 92.0]
 [20.0 'Normal' 'no' 'no' 93.0]
 [17.0 'Normal' 'no' 'no' 93.0]
 [16.0 'Normal' 'no' 'no' 92.0]
 [18.0 'Normal' 'no' 'no' 93.0]
 [20.0 'Normal' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Normal' 'no' 'no' 99.0]
 [29.0 'Normal' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Normal' 'no' 'no' 89.0]
 [25.0 'Normal' 'no' 'yes' 86.0]
 [26.0 'Normal' 'no' 'no' nan]
 [28.0 'Normal' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [nan 'Moderate' 'yes' 'no' 90.0]
 [32.0 'Moderate' 'no' 'no' 89.0]
 [35.0 'Modera

In [7]:
print(y)

['No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'No' 'Yes' 'Yes' 'Yes']





## Handling Missing Data

In [9]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')

imputer.fit(X[:, 0:1])
X[: , 0:1] = imputer.transform(X[:, 0:1])

In [10]:
print(X)




[[10.0 'Normal' 'no' 'no' 97.0]
 [12.0 'Normal' 'no' 'no' 97.0]
 [15.0 'Normal' 'no' 'no' 94.0]
 [10.0 'Normal' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Normal' 'no' 'no' 92.0]
 [20.0 'Normal' 'no' 'no' 93.0]
 [17.0 'Normal' 'no' 'no' 93.0]
 [16.0 'Normal' 'no' 'no' 92.0]
 [18.0 'Normal' 'no' 'no' 93.0]
 [20.0 'Normal' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Normal' 'no' 'no' 99.0]
 [29.0 'Normal' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Normal' 'no' 'no' 89.0]
 [25.0 'Normal' 'no' 'yes' 86.0]
 [26.0 'Normal' 'no' 'no' nan]
 [28.0 'Normal' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [45.130434782608695 'Moderate' 'yes' 'no' 90.0]
 [32.0 'Moderate' 'no' 'no' 89.0]

In [11]:
imputer.fit(X[:, 4:5])
X[: , 4:5] = imputer.transform(X[:, 4:5])


In [12]:
print(X)

[[10.0 'Normal' 'no' 'no' 97.0]
 [12.0 'Normal' 'no' 'no' 97.0]
 [15.0 'Normal' 'no' 'no' 94.0]
 [10.0 'Normal' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Normal' 'no' 'no' 92.0]
 [20.0 'Normal' 'no' 'no' 93.0]
 [17.0 'Normal' 'no' 'no' 93.0]
 [16.0 'Normal' 'no' 'no' 92.0]
 [18.0 'Normal' 'no' 'no' 93.0]
 [20.0 'Normal' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Normal' 'no' 'no' 99.0]
 [29.0 'Normal' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Normal' 'no' 'no' 89.0]
 [25.0 'Normal' 'no' 'yes' 86.0]
 [26.0 'Normal' 'no' 'no' 82.07246376811594]
 [28.0 'Normal' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [45.130434782608695 'Moderate' 'yes' 'no' 90.0]
 [32.0 'Moderate' '

## Encoding Categorical Data

### Encoding independent variables

In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder



In [16]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [1,2,3])], remainder= 'passthrough')
X = np.array(ct.fit_transform(X))



In [17]:
print(X)


[[0.0 0.0 1.0 1.0 0.0 1.0 0.0 10.0 97.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 12.0 97.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 15.0 94.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 10.0 97.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 13.0 94.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 12.0 97.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 13.0 93.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 15.0 92.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 18.0 66.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 19.0 92.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 20.0 93.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 17.0 93.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 16.0 92.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 18.0 93.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 20.0 92.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 25.0 93.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 24.0 92.0]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 26.0 94.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 28.0 99.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 29.0 93.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 30.0 62.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 19.0 89.0]
 [0.0 0.0 1.0 1.0 0.0 0.0 1.0 25.0 86.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 26.0 82.07246376811594]
 [0

In [18]:
print(X.shape)

(70, 9)


### Encoding dependent variables

In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

y = le.fit_transform(y)


In [21]:
print(y)

[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1]


## Splitting data into Test set & Training Set


In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [24]:
print(X_train)

[[1.0 0.0 0.0 0.0 1.0 0.0 1.0 86.0 71.0]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 35.0 92.0]
 [1.0 0.0 0.0 1.0 0.0 0.0 1.0 75.0 72.0]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 42.0 92.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 74.0 75.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 62.0 68.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 24.0 92.0]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 48.0 93.0]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 58.0 70.0]
 [0.0 1.0 0.0 0.0 1.0 1.0 0.0 45.130434782608695 90.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 15.0 92.0]
 [0.0 0.0 1.0 1.0 0.0 0.0 1.0 70.0 88.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 52.0 80.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 60.0 68.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 54.0 70.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 29.0 93.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 78.0 71.0]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 36.0 90.0]
 [0.0 1.0 0.0 0.0 1.0 1.0 0.0 30.0 86.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 50.0 77.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 18.0 93.0]
 [1.0 0.0 0.0 1.0 0.0 0.0 1.0 69.0 53.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 10.0 97.0]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 26.0 94.0]
 [

In [25]:
print(X_test)

[[0.0 0.0 1.0 1.0 0.0 0.0 1.0 25.0 86.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 10.0 97.0]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 68.0 67.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 13.0 94.0]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 59.0 68.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 28.0 99.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 20.0 93.0]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 46.0 91.0]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 53.0 55.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 16.0 92.0]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 38.0 75.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 19.0 92.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 94.0 64.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 12.0 97.0]]


In [26]:
print(y_train)

[1 0 1 0 1 1 0 0 1 0 0 0 1 1 1 0 1 0 0 1 0 1 0 0 1 1 0 0 1 1 1 0 0 1 0 1 0
 1 1 0 0 0 1 1 0 1 1 0 1 0 0 0 1 0 0 1]


In [27]:
print(y_test)

[0 0 1 0 1 0 0 0 1 0 1 0 1 0]


## Feature Scaling

In [29]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,6:] = sc.fit_transform(X_train[:,6:])

X_test[:,6:] = sc.fit_transform(X_test[:,6:])

In [30]:
print(X_train)

[[1.0 0.0 0.0 0.0 1.0 0.0 0.9649012813540153 1.6605950326521113
  -0.9941858494300264]
 [0.0 1.0 0.0 1.0 0.0 0.0 0.9649012813540153 -0.5372483818439074
  0.957435414508189]
 [1.0 0.0 0.0 1.0 0.0 0.0 0.9649012813540153 1.1865503746235584
  -0.9012515035282067]
 [1.0 0.0 0.0 1.0 0.0 1.0 -1.0363754503432019 -0.23558359946210097
  0.957435414508189]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.9649012813540153 1.1434554057118715
  -0.6224484658227473]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.9649012813540153 0.6263157787716319
  -1.2729888871354857]
 [0.0 1.0 0.0 1.0 0.0 1.0 -1.0363754503432019 -1.0112930398724607
  0.957435414508189]
 [0.0 1.0 0.0 1.0 0.0 0.0 0.9649012813540153 0.022986214008018896
  1.0503697604100088]
 [1.0 0.0 0.0 1.0 0.0 1.0 -1.0363754503432019 0.45393590312488535
  -1.0871201953318463]
 [0.0 1.0 0.0 0.0 1.0 1.0 -1.0363754503432019 -0.10067760982551671
  0.7715667227045494]
 [0.0 1.0 0.0 1.0 0.0 1.0 -1.0363754503432019 -1.3991477600776403
  0.957435414508189]
 [0.0 0.0 1.0 1.0 0.0 0.0 0.9649012813

## MODEL TRAINING

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Model ko initialize karo
model = LogisticRegression()

# Model ko train karo
model.fit(X_train, y_train)

# Predictions karo
y_pred = model.predict(X_test)

# Accuracy check karo
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

# Confusion Matrix aur Classification Report print karo
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Accuracy: 100.00%
Confusion Matrix:
[[9 0]
 [0 5]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00         5

    accuracy                           1.00        14
   macro avg       1.00      1.00      1.00        14
weighted avg       1.00      1.00      1.00        14

